# ===============================
# PostgreSQL Configuration (LOCAL)
# ===============================
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Server Context Path
# ===============================
server.servlet.context-path=/api/v1.0

# ===============================
# JPA Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Email Configuration (Brevo)
# ===============================
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=93dee7001@smtp-brevo.com
spring.mail.password=fmHEJ32PaSg1pnzq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=thetes32@gmail.com

# ===============================
# JWT Configuration
# ===============================
jwt.secret=mVPhsK4yN16vnX05wtRPnRp1gdEafpN5U4tGNiKXH9s=
jwt.expiration=86400000
jwt.issuer=MoneyManager

# ===============================
# Frontend and Backend URLs
# ===============================
money.manager.frontend.url=${FRONTEND_URL}
app.activation.url=${BACKEND_URL}